import type { ImageKind, Work, WorkImage } from "@/lib/types";

/**
 * The portfolio, transcribed from Shivjeet Potdar's 2019 monograph.
 * Descriptions expand only on text that appears in that document —
 * medium notes, sites, programmes and the artist's own captions.
 * Nothing here (years, clients, prices, exhibitions) is invented;
 * unknown fields are left null for the Admin to complete.
 */

const img = (
  slug: string,
  file: string,
  kind: ImageKind,
  alt: string,
  order: number,
  width = 2200,
  height = 1495,
  caption?: string,
): WorkImage => ({
  id: `${slug}-${kind}-${order}`,
  url: `/work/${file}`,
  alt,
  kind,
  caption: caption ?? null,
  width,
  height,
  sortOrder: order,
});

const base = {
  status: "published" as const,
  priceVisible: false,
  currency: "INR",
  price: null,
  createdAt: "2019-01-01T00:00:00.000Z",
  updatedAt: "2019-01-01T00:00:00.000Z",
  publishedAt: "2019-01-01T00:00:00.000Z",
};

export const worksSeed: Work[] = [
  {
    ...base,
    id: "w-shiva",
    slug: "shiva",
    title: "Shiva",
    year: null,
    yearSort: 2016,
    discipline: "art",
    kind: "Painting",
    medium: "Oil on canvas",
    dimensions: null,
    summary: "An abstract portrait of Shiva emerging from the deep blue cosmos.",
    description: [
      "An abstract depiction of a portrait of Shiva, emerging from the deep blue cosmos. The face never fully resolves — a mouth in red, a column of pale light where a nose and brow might be, the rest given over to the dark.",
      "The painting works the way the idea does: the god is not an image to be looked at so much as a pressure felt at the edge of sight, a figure the cosmos is still in the act of forming.",
    ],
    statement:
      "I wanted the divine to arrive the way it does in the oldest stories — not as a body, but as something the darkness is busy assembling.",
    collectionSlug: "paint-and-line",
    availability: "enquire",
    featured: true,
    sortOrder: 2,
    coverImage: "/work/shiva.jpg",
    accent: "#2f3d63",
    images: [
      img("shiva", "shiva.jpg", "cover", "Shiva — abstract oil portrait emerging from a deep blue cosmos, with a mouth rendered in red", 0, 2200, 1524),
    ],
    relatedSlugs: ["four-lines-essence", "five-elements"],
  },
  {
    ...base,
    id: "w-ghosts",
    slug: "ghosts-of-takht-mahal",
    title: "Ghosts of Takht Mahal",
    year: null,
    yearSort: 2016,
    discipline: "photography",
    kind: "Miniature & photograph",
    medium: "Miniature built in box board, photo-manipulated",
    dimensions: null,
    location: "Takht Mahal, Bidar Fort",
    summary:
      "The lore says a pregnant woman was buried alive in these walls. A model of the ruin, lit for the ghost.",
    description: [
      "The lore says that a pregnant woman was buried alive in the walls of the Takht Mahal. It is believed that the negative energy still holds those walls standing — that they survived severe bombing by later conquests because of what is sealed inside them.",
      "The scene is a miniature, built in box board and then photographed and manipulated until dusk settles over it. A figure in red carries a lamp across the courtyard toward the ruin, small enough to be a memory of herself.",
    ],
    statement:
      "A ruin keeps its stories in the mortar. I built this one small so I could stand a ghost in it.",
    collectionSlug: "ruin-and-remembrance",
    availability: "enquire",
    featured: true,
    sortOrder: 3,
    coverImage: "/work/ghosts-takht-mahal.jpg",
    accent: "#5b3a4b",
    images: [
      img("ghosts", "ghosts-takht-mahal.jpg", "cover", "Ghosts of Takht Mahal — a box-board miniature of the ruined palace at dusk, a lamp-carrying figure in red crossing the courtyard", 0),
    ],
    relatedSlugs: ["the-formalin-man", "columns-of-past", "the-lost-city"],
  },
  {
    ...base,
    id: "w-lost-city",
    slug: "the-lost-city",
    title: "The Lost City",
    year: null,
    yearSort: 2016,
    discipline: "experimental",
    kind: "Miniature & photograph",
    medium: "Miniature carved in plaster of Paris, painted and photo-manipulated",
    dimensions: null,
    summary:
      "An abandoned city, left to decay, waiting to be revealed in a great expanse of undulating blue desert.",
    description: [
      "An abandoned city left to decay for many years awaits its revelation in a large expanse of undulating blue desert.",
      "The terrain is carved in plaster of Paris, painted, and then photo-manipulated so the horizon reads as endless. A lone traveller and a thread of smoke are the only evidence that the city was ever found again.",
    ],
    statement: null,
    collectionSlug: "miniature-worlds",
    availability: "enquire",
    featured: false,
    sortOrder: 4,
    coverImage: "/work/the-lost-city.jpg",
    accent: "#2f4d7a",
    images: [
      img("lost-city", "the-lost-city.jpg", "cover", "The Lost City — a plaster miniature of a ruined city in a blue desert, shot to read as a vast landscape", 0),
    ],
    relatedSlugs: ["abandoned-for-good", "the-shapeshifting-landscape", "ghosts-of-takht-mahal"],
  },
  {
    ...base,
    id: "w-abandoned",
    slug: "abandoned-for-good",
    title: "Abandoned for Good",
    year: null,
    yearSort: 2016,
    discipline: "experimental",
    kind: "Miniature & photograph",
    medium: "Miniature carved in plaster of Paris, painted and photo-manipulated",
    dimensions: null,
    summary: "As the light diminishes and the darkness takes over, the wilderness lurks in.",
    description: [
      "As the light diminishes and the darkness takes over, the wilderness lurks in.",
      "A settlement carved in plaster, then all but swallowed by night in the photograph — a scatter of lamps along a path is the last of the human hold on the place before it is given back.",
    ],
    statement: null,
    collectionSlug: "miniature-worlds",
    availability: "enquire",
    featured: false,
    sortOrder: 5,
    coverImage: "/work/abandoned-for-good.jpg",
    accent: "#1f2740",
    images: [
      img("abandoned", "abandoned-for-good.jpg", "cover", "Abandoned for Good — a plaster settlement at night, only a line of small lamps still lit along a path", 0),
    ],
    relatedSlugs: ["the-lost-city", "the-shapeshifting-landscape"],
  },
  {
    ...base,
    id: "w-resurrection",
    slug: "resurrection-from-the-ruins",
    title: "Resurrection from the Ruins",
    year: null,
    yearSort: 2017,
    discipline: "architecture",
    kind: "Speculative architecture",
    medium: "3D rendered and photo-manipulated",
    dimensions: null,
    location: "Deccan fort landscape",
    summary: "A tower rises out of a decaying site to make it liveable again.",
    description: [
      "A tower emerges from a decaying place to make it liveable again. It is grafted onto the ruin rather than clearing it — the old stone base is kept, and a stacked, porous structure grows up from it, terraces spilling green.",
      "Rendered in 3D and set back into a photograph of the fort landscape, birds crossing the frame, the proposal argues that a monument can carry new life without being erased to do so.",
    ],
    statement: null,
    collectionSlug: "ruin-and-remembrance",
    availability: "enquire",
    featured: true,
    sortOrder: 6,
    coverImage: "/work/resurrection-from-the-ruins.jpg",
    accent: "#3f6b86",
    images: [
      img("resurrection", "resurrection-from-the-ruins.jpg", "cover", "Resurrection from the Ruins — a tall porous tower growing from the stone base of a ruined fort, terraces planted green", 0),
    ],
    relatedSlugs: ["columns-of-past", "the-act-of-building-is-a-sin", "natures-rage"],
  },
  {
    ...base,
    id: "w-columns",
    slug: "columns-of-past",
    title: "Columns of Past",
    year: null,
    yearSort: 2017,
    discipline: "architecture",
    kind: "Speculative architecture",
    medium: "3D rendered and photo-manipulated",
    dimensions: null,
    summary:
      "Wooden columns lost to explosions return in glass — a quiet reminder of what stood there.",
    description: [
      "The wooden columns once perished by explosions are replaced by glass columns, as a subtle reminder of the past.",
      "In the render, the new columns barely interrupt the light falling through the jaali screens; they mark the grid of the lost hypostyle hall without pretending to be it.",
    ],
    statement: null,
    collectionSlug: "ruin-and-remembrance",
    availability: "enquire",
    featured: false,
    sortOrder: 7,
    coverImage: "/work/columns-of-past.jpg",
    accent: "#7a6a4c",
    images: [
      img("columns", "columns-of-past.jpg", "cover", "Columns of Past — a ruined hall rebuilt with transparent glass columns on the footprint of the lost wooden ones", 0),
    ],
    relatedSlugs: ["resurrection-from-the-ruins", "ghosts-of-takht-mahal", "the-formalin-man"],
  },
  {
    ...base,
    id: "w-formalin",
    slug: "the-formalin-man",
    title: "The Formalin Man",
    year: null,
    yearSort: 2016,
    discipline: "photography",
    kind: "Photograph",
    medium: "Photograph — a conservation worker on the ruins of Bidar Fort",
    dimensions: null,
    location: "Bidar Fort, Karnataka",
    summary:
      "Ruins are history's hard copy. He stands in them to hold off the decay — the fort's formalin man.",
    description: [
      "Architectural ruins stand as a hard copy of history. Here a man stands to battle the decay of those ruins and becomes its formalin man — the preservative that keeps a specimen from turning.",
      "The photograph is of a conservation worker on the ruins of Bidar Fort, framed through the arches so the figure is small, patient, and permanently on duty.",
    ],
    statement:
      "Conservation is a strange, tender job — you are the chemical that stops a thing from becoming what time wants it to become.",
    collectionSlug: "ruin-and-remembrance",
    availability: "enquire",
    featured: true,
    sortOrder: 8,
    coverImage: "/work/the-formalin-man.jpg",
    accent: "#9a5f3c",
    images: [
      img("formalin", "the-formalin-man.jpg", "cover", "The Formalin Man — a conservation worker standing in the arched ruins of Bidar Fort, seen through a run of pointed arches", 0),
    ],
    relatedSlugs: ["ghosts-of-takht-mahal", "columns-of-past", "resurrection-from-the-ruins"],
  },
  {
    ...base,
    id: "w-balance",
    slug: "balance-of-forms",
    title: "Balance of Forms",
    year: null,
    yearSort: 2016,
    discipline: "experimental",
    kind: "Architectural model",
    medium: "Miniature — craft board and mount board",
    dimensions: null,
    summary:
      "A dominant central tower, held in balance by the intricate forms around it.",
    description: [
      "A dominant tower at the centre is balanced by the various intricate forms surrounding it. Smaller pieces assemble into a pathway that climbs to the top of the tower.",
      "The study is built entirely in craft board and mount board — a composition exercise about how much a single mass can be asked to hold before the field around it has to answer back.",
    ],
    statement: null,
    collectionSlug: "miniature-worlds",
    availability: "enquire",
    featured: false,
    sortOrder: 9,
    coverImage: "/work/balance-of-forms.jpg",
    accent: "#6d6357",
    images: [
      img("balance", "balance-of-forms.jpg", "cover", "Balance of Forms — a craft-board model of a tall central tower ringed by smaller stepped forms that build a path to its top", 0, 2200, 1690),
    ],
    relatedSlugs: ["the-act-of-building-is-a-sin", "resurrection-from-the-ruins"],
  },
  {
    ...base,
    id: "w-shapeshifting",
    slug: "the-shapeshifting-landscape",
    title: "The Shape-Shifting Landscape",
    year: null,
    yearSort: 2016,
    discipline: "experimental",
    kind: "Miniature & photograph",
    medium:
      "Miniature in plaster of Paris — mirrors for water, ferns for vegetation — photo-manipulated",
    dimensions: null,
    summary: "Every time the winds whisper, the lands change their faces.",
    description: [
      "Every time the winds whisper, the lands change their faces.",
      "The dunes are plaster of Paris, the ponds are set mirrors, the vegetation is fern; a caravan crosses the ridge. Photographed low and warm, the model becomes a desert that has clearly been a different desert the day before.",
    ],
    statement: null,
    collectionSlug: "miniature-worlds",
    availability: "enquire",
    featured: false,
    sortOrder: 10,
    coverImage: "/work/the-shapeshifting-landscape.jpg",
    accent: "#a8894f",
    images: [
      img("shapeshifting", "the-shapeshifting-landscape.jpg", "cover", "The Shape-Shifting Landscape — a plaster desert with mirror ponds and fern vegetation, a small caravan crossing a dune", 0),
    ],
    relatedSlugs: ["the-lost-city", "abandoned-for-good"],
  },
  {
    ...base,
    id: "w-objects-space",
    slug: "objects-of-space",
    title: "Objects of Space",
    year: null,
    yearSort: 2016,
    discipline: "photography",
    kind: "Photograph",
    medium: "Photograph — the interior of a pierced tin can",
    dimensions: null,
    summary:
      "A photograph taken inside a Coca-Cola can, pierced from outside so its red bleeds into the space within.",
    description: [
      "A photograph taken from the opening of a Coca-Cola tin can, which is poked from outside so that its external red colour projects into the space inside.",
      "The everyday object becomes an incredible space the moment it is given a human scale — a small seated figure at the base turns the can into a lit, domed chamber.",
    ],
    statement:
      "Give any ordinary thing a person to stand in it and it stops being an object. That is most of architecture.",
    collectionSlug: "miniature-worlds",
    availability: "enquire",
    featured: false,
    sortOrder: 11,
    coverImage: "/work/objects-of-space.jpg",
    accent: "#8f7b2f",
    images: [
      img("objects-space", "objects-of-space.jpg", "cover", "Objects of Space — the interior of a Coca-Cola can photographed as a vast domed chamber, a tiny seated figure at its base", 0),
    ],
    relatedSlugs: ["the-shapeshifting-landscape", "balance-of-forms"],
  },
  {
    ...base,
    id: "w-fubar",
    slug: "fubar-first-look",
    title: "FUBAR — First Look",
    year: null,
    yearSort: 2018,
    discipline: "production-design",
    kind: "Title design & first-look poster",
    medium: "Title design and first-look poster",
    dimensions: null,
    role: "Title design, first-look poster",
    client: "A Kiran G. Maney film",
    summary:
      "Title design and the first-look poster for the Kannada feature film FUBAR.",
    description: [
      "The title design and first-look poster for the Kannada feature film FUBAR, a Kiran G. Maney film.",
      "The key art holds the ensemble inside a single fractured colour field — school corridor, festival haze, the lead in a green-and-gold saree — with the FUBAR wordmark cut through the middle so the R breaks away.",
    ],
    statement: null,
    credits: [
      { role: "Director", name: "Kiran G. Maney" },
      { role: "Cast", name: "Shweta Hegde, Harish Raj, Frenny Pinto, Allan Charan" },
      { role: "Cast", name: "Arasu Kumar, Shreyas Udupa, Sachin Acharya, Bhoomi Jonas" },
      { role: "Music", name: "Maestro Music" },
    ],
    collectionSlug: "screen-myth-and-mark",
    availability: "not-for-sale",
    featured: true,
    sortOrder: 12,
    coverImage: "/work/fubar.jpg",
    accent: "#3b6b52",
    images: [
      img("fubar", "fubar.jpg", "cover", "FUBAR first-look poster — the ensemble cast inside a fractured colour field with the FUBAR wordmark cut across the centre", 0),
    ],
    relatedSlugs: ["terror-nature", "lore-poster"],
  },
  {
    ...base,
    id: "w-terror-nature",
    slug: "terror-nature",
    title: "Terror Nature",
    year: null,
    yearSort: 2017,
    discipline: "production-design",
    kind: "Character design & poster",
    medium: "Character design and short-film poster",
    dimensions: null,
    role: "Character design, poster",
    summary:
      "A character design for the short film Terror Nature — a nature god in the clothes of a poor young man.",
    description: [
      "A character design for the short film Terror Nature: a nature god in the attire of a poor young man.",
      "Paper crown, a phone held up like an offering, a length of red cloth unravelling into the storm behind him — divinity dressed down to the point where you would walk past it.",
    ],
    statement: null,
    collectionSlug: "screen-myth-and-mark",
    availability: "not-for-sale",
    featured: false,
    sortOrder: 13,
    coverImage: "/work/terror-nature.jpg",
    accent: "#b23b30",
    images: [
      img("terror-nature", "terror-nature.jpg", "cover", "Terror Nature — a young man with a paper crown against a stormy sky, a long red cloth unspooling into the clouds", 0, 2200, 874),
    ],
    relatedSlugs: ["fubar-first-look", "lore-poster"],
  },
  {
    ...base,
    id: "w-four-lines",
    slug: "four-lines-essence",
    title: "Four Lines, an Essence",
    year: null,
    yearSort: 2015,
    discipline: "art",
    kind: "Drawing",
    medium: "Ink on paper",
    dimensions: null,
    summary:
      "Mountains, a sea, the rushing waves, the horizon, the wind, the reach of the land and the sky — all of it in four lines.",
    description: [
      "A scenery with mountains, a huge sea, the waves rushing, the horizon, the wind direction, the extent of the landscape and the sky — all of it expressed in as little as four lines.",
      "A reduction exercise, and a statement of intent: how far can a drawing be pared back before the landscape stops arriving?",
    ],
    statement:
      "Four lines. If the sea still comes in, you have found the essence. If it doesn't, you were drawing decoration.",
    collectionSlug: "paint-and-line",
    availability: "enquire",
    featured: false,
    sortOrder: 14,
    coverImage: "/work/four-lines-essence.jpg",
    accent: "#8a7d63",
    images: [
      img("four-lines", "four-lines-essence.jpg", "cover", "Four Lines, an Essence — a minimal ink drawing on cream paper reducing an entire seascape to four gestural lines", 0, 2200, 1407),
    ],
    relatedSlugs: ["shiva", "five-elements"],
  },
  {
    ...base,
    id: "w-lore",
    slug: "lore-poster",
    title: "LORE — Prime Original",
    year: null,
    yearSort: 2018,
    discipline: "graphic",
    kind: "Key art / poster design",
    medium: "Drawing and 3D software, photo-manipulated",
    dimensions: null,
    role: "Poster design",
    client: "Concept key art — Prime Video series LORE",
    summary:
      "Two poster directions for the Prime Original series LORE — the show's tools and horrors built into the title.",
    description: [
      "Poster design for the Prime Original series LORE. In the first direction the tools and horrors of the show are embedded directly into the letters — a hangman's noose, a plague mask, a scythe, a pentagram struck through the O.",
      "The show tells the story of events in history, inscribed in blood. The second direction takes that literally: the title is carved into rock and the cuts run red, modelled in 3D and manipulated back into stone.",
    ],
    statement: null,
    collectionSlug: "screen-myth-and-mark",
    availability: "not-for-sale",
    featured: true,
    sortOrder: 15,
    coverImage: "/work/lore-tools.jpg",
    accent: "#7c7f7a",
    images: [
      img("lore-tools", "lore-tools.jpg", "cover", "LORE poster — the title drawn from the tools and horrors of the series, a pentagram through the O, on aged paper", 0),
      img("lore-blood", "lore-blood.jpg", "gallery", "LORE poster, second direction — the title carved into rock with the cuts filled red like inscribed blood", 1),
    ],
    relatedSlugs: ["fubar-first-look", "terror-nature", "india-coffee-house-rebrand"],
  },
  {
    ...base,
    id: "w-natures-rage",
    slug: "natures-rage",
    title: "Nature's Rage",
    year: null,
    yearSort: 2017,
    discipline: "architecture",
    kind: "Architecture — residential",
    medium: "3D rendered and photo-manipulated",
    dimensions: null,
    location: "Turahalli forest edge, Bengaluru",
    role: "Design",
    summary:
      "A residential complex on the edge of Turahalli forest, redesigned so that you live a forest rather than view one.",
    description: [
      "How would you like to hear a koel in the mornings, to catch a peacock dancing at your window, to have fresh breeze through your lungs and a flower garden at the back — the lush green of the forest and urban life in the same address?",
      "The site is an existing residential complex standing at the edge of Turahalli forest, Bengaluru. The intervention promotes living a forest versus viewing a forest: a lattice structure whose surface is a growth medium, so the building's skin is gradually replaced by vegetation. Water ponds at the green edge draw fauna; fruiting and flowering plants bring in birds, beetles and butterflies; the section lets nature's rainwater runoff continue uninterrupted.",
      "It celebrates the spirit of growing nature — and so Nature's Rage begins through this design, and continues.",
    ],
    statement:
      "The building is not the point. The point is whether, in twenty years, you can still tell where it ends and the forest begins.",
    concept:
      "Nature space, semi-public space and private apartments interlocked in a single diagonal lattice. Green cover filters the west sun to a glare-free view. Earth-coloured structure so the mass reads as ground, not object.",
    collectionSlug: "building-and-spatial-practice",
    availability: "enquire",
    featured: true,
    sortOrder: 16,
    coverImage: "/work/natures-rage-render.jpg",
    accent: "#4b6b3a",
    images: [
      img("natures-rage-render", "natures-rage-render.jpg", "cover", "Nature's Rage — a large diagonal green-clad structure merging into the Turahalli forest landscape, a peacock in the foreground", 0),
      img("natures-rage-section", "natures-rage-section.jpg", "drawing", "Nature's Rage — a section through the forest edge showing the lattice building stepping down from Turahalli forest to Bengaluru city, and an interior overtaken by plants and birds", 1),
    ],
    relatedSlugs: ["the-act-of-building-is-a-sin", "resurrection-from-the-ruins", "sumans-residence"],
  },
  {
    ...base,
    id: "w-act-of-building",
    slug: "the-act-of-building-is-a-sin",
    title: "The Act of Building Itself Is a Sin",
    year: null,
    yearSort: 2017,
    discipline: "architecture",
    kind: "Speculative architecture",
    medium: "Miniature carved in plaster of Paris, painted and photo-manipulated",
    dimensions: null,
    location: "A disused quarry",
    role: "Design",
    summary:
      "If building at all is a sin, then build on the dead ground — the scarred face of a quarry — and bring it back to life.",
    description: [
      "The very fact of building a building, and taking a valuable piece of land to do it, is unsustainable. But care taken over what is built, and on what kind of land, can change that. A land space that is an eco-void — little ecosystem, non-regenerating, such as the scarred face of a quarry — can carry a permanent structure that reclaims the dead space and makes it alive again.",
      "The proposal threads a programme through the cut rock: an auditorium braced against the quarry wall, semi-open workshops on the floor, a cycle path and bridge stitching the two faces together, and a transformable structure at the quarry-life intersection.",
    ],
    statement:
      "You cannot build without taking something. So take the ground nobody wants, and give it back more than you took.",
    concept:
      "Quarry–life intersection · buttressed auditorium · semi-open workshops · cycle pathway and bridge · transformable structure.",
    collectionSlug: "building-and-spatial-practice",
    availability: "enquire",
    featured: false,
    sortOrder: 17,
    coverImage: "/work/the-act-of-building-is-a-sin.jpg",
    accent: "#6f6152",
    images: [
      img("act-building", "the-act-of-building-is-a-sin.jpg", "cover", "The Act of Building Itself Is a Sin — a plaster model of an architectural programme threaded into the cut face of a quarry, with a section alongside", 0, 2200, 874),
    ],
    relatedSlugs: ["natures-rage", "resurrection-from-the-ruins", "balance-of-forms"],
  },
  {
    ...base,
    id: "w-pavilion",
    slug: "pavilion-rvca-x",
    title: "Pavilion RVCA X",
    year: "2017",
    yearSort: 2017,
    discipline: "spatial-design",
    kind: "Built installation",
    medium: "Bent steel and stretched jute fabric",
    dimensions: null,
    location: "RV College of Architecture, Bengaluru",
    role: "Design and build",
    summary:
      "A curvilinear pavilion for the RVCA exhibition, 2017 — bent steel anchored to the ground, framing stretched jute.",
    description: [
      "A curvilinear pavilion running through the central congregational area of RV College of Architecture during the 2017 exhibition.",
      "8 torr steel is bent to shape and anchored into the landscape; stretched jute fabric is framed within it. The result is a soft, structural canopy that people walk under, sit against and photograph — a piece of built spatial design rather than a drawing of one.",
    ],
    statement: null,
    collectionSlug: "building-and-spatial-practice",
    availability: "not-for-sale",
    featured: true,
    sortOrder: 18,
    coverImage: "/work/pavilion-rvca-x.jpg",
    accent: "#9c6b46",
    images: [
      img("pavilion", "pavilion-rvca-x.jpg", "cover", "Pavilion RVCA X — a curved canopy of bent steel and stretched jute fabric installed across a college courtyard, during construction and completed", 0, 2200, 874),
    ],
    relatedSlugs: ["natures-rage", "rkva-bidar", "sumans-residence"],
  },
  {
    ...base,
    id: "w-sumans",
    slug: "sumans-residence",
    title: "Suman's Residence",
    year: null,
    yearSort: 2018,
    discipline: "architecture",
    kind: "Architecture — residential",
    medium: "3D rendered",
    dimensions: null,
    location: "Northern Karnataka",
    role: "Design",
    summary:
      "A house for a hot, dry climate — a breathable façade of climbers on a steel grill, rising from exposed-brick planters.",
    description: [
      "A residence in northern Karnataka, where the climate is hot and dry.",
      "The elevation is designed around a steel grill that lifts out of exposed-brick planters; climbers are trained over it so the façade fills in with living shade. The house ends up with a breathable, nature-welcoming front that is right for the weather it has to stand in.",
    ],
    statement: null,
    collectionSlug: "building-and-spatial-practice",
    availability: "enquire",
    featured: false,
    sortOrder: 19,
    coverImage: "/work/sumans-residence.jpg",
    accent: "#8a6a44",
    images: [
      img("sumans", "sumans-residence.jpg", "cover", "Suman's Residence — a rendered elevation of a white house in northern Karnataka with brick planters and a steel grill carrying climbing plants", 0),
    ],
    relatedSlugs: ["natures-rage", "rkva-bidar", "pavilion-rvca-x"],
  },
  {
    ...base,
    id: "w-rkva",
    slug: "rkva-bidar",
    title: "Ramakrishna Vivekananda Ashrama, Bidar",
    year: null,
    yearSort: 2018,
    discipline: "architecture",
    kind: "Architecture — institutional",
    medium: "3D rendered",
    dimensions: null,
    location: "Bidar, Karnataka",
    role: "Elevation design",
    summary:
      "An elevation for the Bidar ashrama that takes the Adil Shahi motifs of the city and says them in a contemporary voice.",
    description: [
      "The elevation design of the Ramakrishna Vivekananda Ashrama, Bidar, derives some of its architectural motifs from the native Adil Shahi architecture of Bidar and expresses them in a contemporary style.",
      "Arched niches and a crenellated parapet quote the old city; the red vertical fins and the flat planes between them are the present day. The building belongs to Bidar without being a costume of it.",
    ],
    statement: null,
    collectionSlug: "building-and-spatial-practice",
    availability: "not-for-sale",
    featured: false,
    sortOrder: 20,
    coverImage: "/work/rkva-bidar.jpg",
    accent: "#9a4b3c",
    images: [
      img("rkva", "rkva-bidar.jpg", "cover", "Ramakrishna Vivekananda Ashrama, Bidar — a rendered elevation with arched niches and a crenellated parapet quoting Adil Shahi architecture, with contemporary red vertical fins", 0),
    ],
    relatedSlugs: ["sumans-residence", "columns-of-past", "pavilion-rvca-x"],
  },
  {
    ...base,
    id: "w-black-taj",
    slug: "the-black-taj-mahal",
    title: "The Black Taj Mahal",
    year: null,
    yearSort: 2018,
    discipline: "architecture",
    kind: "Speculative architecture",
    medium: "3D rendered and photo-manipulated",
    dimensions: null,
    location: "Yamuna riverfront, opposite the Taj Mahal, Agra",
    role: "Design",
    summary:
      "The Black Taj that was meant to stand across the Yamuna — rebuilt here as black marble blocks holding a glass wall for love stories.",
    description: [
      "On the other side of the Yamuna, a Black Taj Mahal was supposed to exist. This proposal builds it as a composition of black marble blocks, placed in symmetry and balance with the Taj Mahal, holding a huge glass wall.",
      "On that glass wall, people write their love — their stories, the names of the ones they love — inscribing their memory onto the Monument of Love. With the Taj as its backdrop it becomes a performance platform, and in the quiet hours a museum of love stories.",
    ],
    statement:
      "The Taj is a tomb pretending to be a love story. The Black Taj could just be the love story.",
    collectionSlug: "ruin-and-remembrance",
    availability: "enquire",
    featured: true,
    sortOrder: 21,
    coverImage: "/work/the-black-taj-mahal.jpg",
    accent: "#3f4750",
    images: [
      img("black-taj", "the-black-taj-mahal.jpg", "cover", "The Black Taj Mahal — black marble blocks and a large glass wall on the Yamuna riverbank, the white Taj Mahal across the water", 0, 2200, 874),
    ],
    relatedSlugs: ["resurrection-from-the-ruins", "columns-of-past", "natures-rage"],
  },
  {
    ...base,
    id: "w-india-coffee",
    slug: "india-coffee-house-rebrand",
    title: "The Divine Coffee — India Coffee House",
    year: null,
    yearSort: 2018,
    discipline: "graphic",
    kind: "Identity / rebranding",
    medium: "Logo and identity design",
    dimensions: null,
    role: "Identity design",
    summary:
      "A rebrand of the India Coffee House that pours the Samudra Manthan into the cup.",
    description: [
      "A rebranding of the India Coffee House that introduces Hindu mythological elements into the mark.",
      "The churning of the ocean of milk — the Devas on one side, the Asuras on the other, pulling Mount Mandara wrapped in the serpent king Vasuki, to win the nectar of immortality — is redrawn as a single red emblem, the coffee cup where the mountain's peak should be. The line reads: The Divine Coffee.",
    ],
    statement: null,
    collectionSlug: "screen-myth-and-mark",
    availability: "not-for-sale",
    featured: false,
    sortOrder: 22,
    coverImage: "/work/india-coffee-house.jpg",
    accent: "#9c3b32",
    images: [
      img("india-coffee", "india-coffee-house.jpg", "cover", "The Divine Coffee — a red emblem for the India Coffee House rendering the churning of the ocean of milk with a coffee cup at its summit", 0, 2200, 1654),
    ],
    relatedSlugs: ["five-elements", "lore-poster"],
  },
  {
    ...base,
    id: "w-flush-credits",
    slug: "flush-credits",
    title: "Flush Credits",
    year: null,
    yearSort: 2017,
    discipline: "experimental",
    kind: "Speculative product design",
    medium: "Concept — product and system design",
    dimensions: null,
    role: "Concept and system design",
    summary:
      "An infotech flush plate that pays a household in bio-gas credits for using the toilet instead of the open.",
    description: [
      "An infotech flush plate for public toilets. A fingerprint scanner on the plate identifies the person; on recognition it blinks green and triggers the flush. Every use is logged to a web account for that person or family.",
      "Night soil collected becomes bio-gas. For a family of four, a day's use generates enough fuel to cook a day's food — replacing the dry wood that would otherwise be burned, with its emissions, in rural areas. The credits earned are redeemable, which turns using a toilet into a small income and makes open defecation the worse deal.",
      "Quantity sensors meter the water released so nothing is wasted; a green-red indicator flags incorrect operation; a jet of air dries the finger after scanning.",
    ],
    statement:
      "Public health is usually sold as a duty. It works better sold as a return.",
    collectionSlug: "screen-myth-and-mark",
    availability: "not-for-sale",
    featured: false,
    sortOrder: 23,
    coverImage: "/work/flush-credits.jpg",
    accent: "#4a4f55",
    images: [
      img("flush-credits", "flush-credits.jpg", "cover", "Flush Credits — a white fingerprint-scanning flush plate marked TAP TO FLUSH, with a system diagram linking toilet, bio-gas and a web account", 0, 2200, 778),
    ],
    relatedSlugs: ["five-elements", "india-coffee-house-rebrand"],
  },
  {
    ...base,
    id: "w-five-elements",
    slug: "five-elements",
    title: "Five Elements",
    year: null,
    yearSort: 2015,
    discipline: "graphic",
    kind: "Logo / mark",
    medium: "Logo design",
    dimensions: null,
    summary:
      "A mark for the five elements — fire, water, earth, air and space, each given a single line.",
    description: [
      "A logo design representing the five elements of nature, each reduced to one mark: fire is a wavy line, water a double wavy line, earth a straight line, air a dotted line, and space a circle.",
      "Assembled, the five lines make a single geometric figure — the seed of the Conscious Omnium identity.",
    ],
    statement: null,
    collectionSlug: "paint-and-line",
    availability: "not-for-sale",
    featured: false,
    sortOrder: 24,
    coverImage: "/work/five-elements.jpg",
    accent: "#b5642a",
    images: [
      img("five-elements", "five-elements.jpg", "cover", "Five Elements — a geometric logo of circle, square and triangles overlaid with fire and water, representing the five elements of nature", 0),
    ],
    relatedSlugs: ["india-coffee-house-rebrand", "four-lines-essence", "shiva"],
  },
];
