import type { Work } from "@/lib/types";

/**
 * The gallery — Shivjeet Potdar's painting practice, transcribed verbatim
 * from the client-supplied artwork PDFs/pptx (see
 * `WEBSITE DESIGN MATERIAL/pages/gallery`). Descriptions, medium,
 * dimensions and price expand only on what the artist himself wrote for
 * each piece; where the source material didn't cover a work (three Duality
 * titles, one untitled piece), those fields are left null rather than
 * invented.
 */

const base = {
  status: "published" as const,
  priceVisible: false,
  currency: "INR",
  price: null,
};

export const worksSeed: Work[] = [
  {
    ...base,
    id: "w-gallery-breath-and-the-mind",
    slug: "breath-and-the-mind",
    title: "Breath and the Mind",
    year: "2026",
    yearSort: 2026,
    discipline: "art",
    kind: "Painting",
    medium: "Oil pastels on black paper",
    dimensions: "54 × 67 cm",
    summary: "The relationship between breath and mind, traced through repeated returns to the point where attention keeps slipping and keeps coming back.",
    description: [
      "The journey begins with a black canvas — a space before form, representing stillness and possibility. Through Anapana meditation, attention moves towards the breath: the touch of air at the nostrils, the movement through the body, and subtle sensations around the forehead.",
      "Thoughts continue to arise and pull attention away, but awareness returns again and again to the breath. This painting explores the relationship between breath and mind — the constant movement between distraction and observation, thought and presence. A visual reflection on the process of becoming aware.",
    ],
    statement: null,
    process: null,
    collectionSlug: "black-canvas",
    availability: "available",
    price: 65000,
    priceVisible: true,
    featured: false,
    sortOrder: 25,
    coverImage: "/gallery/black-canvas/breath-and-the-mind.jpg",
    images: [
      { id: "breath-and-the-mind-cover", url: "/gallery/black-canvas/breath-and-the-mind.jpg", alt: "Breath and the Mind — Shivjeet Potdar, Oil pastels on black paper", kind: "cover", caption: null, width: 2400, height: 1874, sortOrder: 0 },
      { id: "breath-and-the-mind-installation", url: "/gallery/black-canvas/breath-and-the-mind-context.jpg", alt: "Breath and the Mind — installation view", kind: "installation", caption: null, width: 2400, height: 1600, sortOrder: 1 },
    ],
    relatedSlugs: ["subtle-currents","the-tree-house","vortex-of-awareness"],
  },
  {
    ...base,
    id: "w-gallery-subtle-currents",
    slug: "subtle-currents",
    title: "Subtle Currents",
    year: "2026",
    yearSort: 2026,
    discipline: "art",
    kind: "Painting",
    medium: "Oil pastels on black paper",
    dimensions: "54 × 67 cm",
    summary: "A narrowing of focus to the space between the nostrils and the upper lip, and the almost-invisible movements found there.",
    description: [
      "Attention moves deeper into a smaller field of observation — the space between the nostrils and the upper lip, where the breath gently touches the body. The slightest sensations become visible: the movement of air, the changing waves of feeling, and the subtle currents that are usually unnoticed.",
      "Thoughts continue to arise and pull attention away, but awareness returns again and again. This painting explores the refinement of attention — discovering the depth within a single breath and the invisible movements that exist within each moment.",
    ],
    statement: null,
    process: null,
    collectionSlug: "black-canvas",
    availability: "available",
    price: 55000,
    priceVisible: true,
    featured: false,
    sortOrder: 26,
    coverImage: "/gallery/black-canvas/subtle-currents.jpg",
    images: [
      { id: "subtle-currents-cover", url: "/gallery/black-canvas/subtle-currents.jpg", alt: "Subtle Currents — Shivjeet Potdar, Oil pastels on black paper", kind: "cover", caption: null, width: 2400, height: 1874, sortOrder: 0 },
      { id: "subtle-currents-installation", url: "/gallery/black-canvas/subtle-currents-context.jpg", alt: "Subtle Currents — installation view", kind: "installation", caption: null, width: 2400, height: 1600, sortOrder: 1 },
    ],
    relatedSlugs: ["breath-and-the-mind","the-tree-house","vortex-of-awareness"],
  },
  {
    ...base,
    id: "w-gallery-the-tree-house",
    slug: "the-tree-house",
    title: "The Tree House",
    year: "2026",
    yearSort: 2026,
    discipline: "art",
    kind: "Painting",
    medium: "Oil pastels on black paper",
    dimensions: "54 × 67 cm",
    summary: "A meditation that wandered toward a real design brief — a tree house for a friend's farm — and let the thought become the painting instead of resisting it.",
    description: [
      "The meditation began with observing the breath, but attention moved towards a thought — the design of a tree house for a friend's farm. A place to work, observe the land, and remain connected with nature while working remotely. Instead of resisting the thought, I followed it.",
      "The structure, the space, the relationship between architecture and landscape began to take form on the canvas. This work explores the meeting point of meditation and creativity — where a thought becomes a design, and design becomes a form of observation.",
    ],
    statement: null,
    process: null,
    collectionSlug: "black-canvas",
    availability: "available",
    price: 75000,
    priceVisible: true,
    featured: false,
    sortOrder: 27,
    coverImage: "/gallery/black-canvas/the-tree-house.jpg",
    images: [
      { id: "the-tree-house-cover", url: "/gallery/black-canvas/the-tree-house.jpg", alt: "The Tree House — Shivjeet Potdar, Oil pastels on black paper", kind: "cover", caption: null, width: 2400, height: 1874, sortOrder: 0 },
      { id: "the-tree-house-installation", url: "/gallery/black-canvas/the-tree-house-context.jpg", alt: "The Tree House — installation view", kind: "installation", caption: null, width: 2400, height: 1600, sortOrder: 1 },
    ],
    relatedSlugs: ["breath-and-the-mind","subtle-currents","vortex-of-awareness"],
  },
  {
    ...base,
    id: "w-gallery-vortex-of-awareness",
    slug: "vortex-of-awareness",
    title: "Vortex of Awareness",
    year: "2026",
    yearSort: 2026,
    discipline: "art",
    kind: "Painting",
    medium: "Oil pastels on black paper",
    dimensions: "54 × 67 cm",
    summary: "Attention moved through the body from head to toe until the sensations converged into something felt as a single inner vortex.",
    description: [
      "Through meditation, attention moves through the body — observing sensations from head to toe and back again. As awareness deepens, these subtle sensations begin to feel like waves, converging into an inner movement — a vortex within the body.",
      "For brief moments, the outside world fades, leaving only observation and experience. This painting explores the relationship between sensation, awareness, and the continuous journey of understanding the self through observation.",
    ],
    statement: null,
    process: null,
    collectionSlug: "black-canvas",
    availability: "available",
    price: 75000,
    priceVisible: true,
    featured: false,
    sortOrder: 28,
    coverImage: "/gallery/black-canvas/vortex-of-awareness.jpg",
    images: [
      { id: "vortex-of-awareness-cover", url: "/gallery/black-canvas/vortex-of-awareness.jpg", alt: "Vortex of Awareness — Shivjeet Potdar, Oil pastels on black paper", kind: "cover", caption: null, width: 2400, height: 1874, sortOrder: 0 },
      { id: "vortex-of-awareness-installation", url: "/gallery/black-canvas/vortex-of-awareness-context.jpg", alt: "Vortex of Awareness — installation view", kind: "installation", caption: null, width: 2400, height: 1600, sortOrder: 1 },
    ],
    relatedSlugs: ["breath-and-the-mind","subtle-currents","the-tree-house"],
  },
  {
    ...base,
    id: "w-gallery-shape-of-belief",
    slug: "shape-of-belief",
    title: "Shape of Belief",
    year: "2026",
    yearSort: 2026,
    discipline: "art",
    kind: "Painting",
    medium: "Acrylic and chalk powder on black paper",
    dimensions: "54 × 67 cm",
    summary: "Transparent gum laid on black paper first, powder colour added after — belief, like perception, giving shape to a pattern that already existed.",
    description: [
      "This work begins with a question: do we experience truth as it is, or do we experience the meaning we create around it? The painting starts with transparent gum applied on the black surface — an invisible structure waiting to be revealed. Powder colour is then introduced, exposing patterns that were already formed before they became visible.",
      "The process becomes a reflection of perception itself. We observe, interpret, connect fragments, and create meaning. Gradually, belief gives shape to what we see. This painting explores the space between reality and interpretation — between what exists and what the mind reveals.",
    ],
    statement: null,
    process: null,
    collectionSlug: "black-canvas",
    availability: "available",
    price: 75000,
    priceVisible: true,
    featured: true,
    sortOrder: 29,
    coverImage: "/gallery/black-canvas/shape-of-belief.jpg",
    images: [
      { id: "shape-of-belief-cover", url: "/gallery/black-canvas/shape-of-belief.jpg", alt: "Shape of Belief — Shivjeet Potdar, Acrylic and chalk powder on black paper", kind: "cover", caption: null, width: 2400, height: 1874, sortOrder: 0 },
      { id: "shape-of-belief-installation", url: "/gallery/black-canvas/shape-of-belief-context.jpg", alt: "Shape of Belief — installation view", kind: "installation", caption: null, width: 2400, height: 1600, sortOrder: 1 },
    ],
    relatedSlugs: ["breath-and-the-mind","subtle-currents","the-tree-house"],
  },
  {
    ...base,
    id: "w-gallery-the-light-attracts-everything",
    slug: "the-light-attracts-everything",
    title: "The Light Attracts Everything",
    year: "2026",
    yearSort: 2026,
    discipline: "art",
    kind: "Painting",
    medium: "Acrylic on Ivory paper",
    dimensions: "56 × 71 cm",
    summary: "A 3 a.m. meditation, documented on camera for the first time, as terrace lights drew bees out of the dark and distraction became the subject.",
    description: [
      "A 3 AM meditation led into this painting process. For the first time, decided to document the experience and speak in front of the camera. As the terrace lights drew bees from the darkness, the act of creating also brought distraction, fear, movement, and awareness to the surface.",
      "This work became less about achieving stillness and more about observing everything that gathers around light.",
    ],
    statement: null,
    process: "Watch the process: https://youtu.be/4laH2RzzHyg",
    collectionSlug: "states-of-attention",
    availability: "available",
    price: 60000,
    priceVisible: true,
    featured: true,
    sortOrder: 30,
    coverImage: "/gallery/states-of-attention/the-light-attracts-everything.jpg",
    images: [
      { id: "the-light-attracts-everything-cover", url: "/gallery/states-of-attention/the-light-attracts-everything.jpg", alt: "The Light Attracts Everything — Shivjeet Potdar, Acrylic on Ivory paper", kind: "cover", caption: null, width: 2400, height: 1874, sortOrder: 0 },
      { id: "the-light-attracts-everything-installation", url: "/gallery/states-of-attention/the-light-attracts-everything-context.jpg", alt: "The Light Attracts Everything — installation view", kind: "installation", caption: null, width: 2400, height: 1600, sortOrder: 1 },
    ],
    relatedSlugs: ["symmetry-in-the-swarm","concentric-emergence","pyre-for-perspective"],
  },
  {
    ...base,
    id: "w-gallery-symmetry-in-the-swarm",
    slug: "symmetry-in-the-swarm",
    title: "Symmetry in the Swarm",
    year: "2026",
    yearSort: 2026,
    discipline: "art",
    kind: "Painting",
    medium: "Acrylic on Ivory paper",
    dimensions: "56 × 71 cm",
    summary: "As the bees at the terrace light kept gathering, deeper focus turned their chaos into afterimages — symmetrical forms emerging within the swarm.",
    description: [
      "This emerged from observing distraction, fear, and the gradual ability to remain present. As bees gathered around the terrace lights, the chaos of movement became the subject of observation. With deeper focus, the external world began to fade, and patterns started appearing through afterimages — symmetrical forms emerging within the swarm.",
      "The painting explores the hidden order within apparent chaos, and how attention can transform disturbance into perception.",
    ],
    statement: null,
    process: "Watch the process: https://youtu.be/ZdW_NNWwjWE",
    collectionSlug: "states-of-attention",
    availability: "available",
    price: 60000,
    priceVisible: true,
    featured: false,
    sortOrder: 31,
    coverImage: "/gallery/states-of-attention/symmetry-in-the-swarm.jpg",
    images: [
      { id: "symmetry-in-the-swarm-cover", url: "/gallery/states-of-attention/symmetry-in-the-swarm.jpg", alt: "Symmetry in the Swarm — Shivjeet Potdar, Acrylic on Ivory paper", kind: "cover", caption: null, width: 2400, height: 1874, sortOrder: 0 },
      { id: "symmetry-in-the-swarm-installation", url: "/gallery/states-of-attention/symmetry-in-the-swarm-context.jpg", alt: "Symmetry in the Swarm — installation view", kind: "installation", caption: null, width: 2400, height: 1600, sortOrder: 1 },
    ],
    relatedSlugs: ["the-light-attracts-everything","concentric-emergence","pyre-for-perspective"],
  },
  {
    ...base,
    id: "w-gallery-concentric-emergence",
    slug: "concentric-emergence",
    title: "Concentric Emergence",
    year: "2026",
    yearSort: 2026,
    discipline: "art",
    kind: "Painting",
    medium: "Acrylic on Ivory paper",
    dimensions: "56 × 71 cm",
    summary: "The camera was still there, but the mind had begun to move past it — what stayed visible were concentric afterimages expanding around a growing centre of light.",
    description: [
      "The camera was still present, but it no longer occupied the space the same way. The bees remained around the light, yet the mind had begun to move past distraction. What stayed visible were the afterimages — concentric formations expanding and dissolving around a growing centre of light.",
      "The experience felt similar to searching for light while trapped inside fabric — like the brief moment when a T-shirt catches around the head and the eyes instinctively move toward the opening. This painting emerged from that sensation of perception pushing itself toward clarity.",
    ],
    statement: null,
    process: "Watch the process: https://youtu.be/Fc9Obr-xNKI",
    collectionSlug: "states-of-attention",
    availability: "available",
    price: 85000,
    priceVisible: true,
    featured: false,
    sortOrder: 32,
    coverImage: "/gallery/states-of-attention/concentric-emergence.jpg",
    images: [
      { id: "concentric-emergence-cover", url: "/gallery/states-of-attention/concentric-emergence.jpg", alt: "Concentric Emergence — Shivjeet Potdar, Acrylic on Ivory paper", kind: "cover", caption: null, width: 2400, height: 1874, sortOrder: 0 },
      { id: "concentric-emergence-installation", url: "/gallery/states-of-attention/concentric-emergence-context.jpg", alt: "Concentric Emergence — installation view", kind: "installation", caption: null, width: 2400, height: 1600, sortOrder: 1 },
    ],
    relatedSlugs: ["the-light-attracts-everything","symmetry-in-the-swarm","pyre-for-perspective"],
  },
  {
    ...base,
    id: "w-gallery-pyre-for-perspective",
    slug: "pyre-for-perspective",
    title: "Pyre for Perspective",
    year: "2026",
    yearSort: 2026,
    discipline: "art",
    kind: "Painting",
    medium: "Burnt on Ivory paper",
    dimensions: "56 × 71 cm",
    summary: "A disturbance during meditation — that thoughts about painting never stop arising — led to burning the paper itself and using the burn marks to form an eye.",
    description: [
      "During meditation, a disturbance arose from the thought that thoughts themselves continue to arise endlessly. The act of painting began to feel performative — an image repeating itself through habit, observation, and identity. A question remained: if art is meant to liberate, what must first be burned?",
      "Began burning paper and using the burn marks themselves to form an eye-like structure on the canvas. The process became less about creating an image and more about confronting perspective through destruction. This work emerged from an attempt to burn perspective itself.",
    ],
    statement: null,
    process: "Watch the process: https://youtu.be/xvQT-e2y8OE",
    collectionSlug: "states-of-attention",
    availability: "available",
    price: 65000,
    priceVisible: true,
    featured: false,
    sortOrder: 33,
    coverImage: "/gallery/states-of-attention/pyre-for-perspective.jpg",
    images: [
      { id: "pyre-for-perspective-cover", url: "/gallery/states-of-attention/pyre-for-perspective.jpg", alt: "Pyre for Perspective — Shivjeet Potdar, Burnt on Ivory paper", kind: "cover", caption: null, width: 2400, height: 1874, sortOrder: 0 },
      { id: "pyre-for-perspective-installation", url: "/gallery/states-of-attention/pyre-for-perspective-context.jpg", alt: "Pyre for Perspective — installation view", kind: "installation", caption: null, width: 2400, height: 1600, sortOrder: 1 },
    ],
    relatedSlugs: ["the-light-attracts-everything","symmetry-in-the-swarm","concentric-emergence"],
  },
  {
    ...base,
    id: "w-gallery-the-canvas-wouldnot-empty",
    slug: "the-canvas-wouldnot-empty",
    title: "The Canvas Wouldnot Empty",
    year: "2026",
    yearSort: 2026,
    discipline: "art",
    kind: "Painting",
    medium: "Acrylic on Ivory paper",
    dimensions: "56 × 71 cm",
    summary: "An attempt to cover the canvas in black and find emptiness — undone, layer after layer, by a mind that kept moving.",
    description: [
      "The meditation began, but thoughts arrived faster than silence — thoughts about painting, the camera, people watching, and the future. Instead of resisting them, placed them onto the canvas. I tried covering everything in black, searching for emptiness. But the mind was still active, still moving. Colours returned, one layer washing over another, like thoughts replacing thoughts.",
      "This work explores a question: If thoughtlessness is not the goal, can deep awareness itself become meditation? Perhaps painting is also a meditation — not by escaping thought, but by moving completely through it.",
    ],
    statement: null,
    process: "Watch the process: https://youtu.be/PFnRwOx9Z3U",
    collectionSlug: "states-of-attention",
    availability: "available",
    price: 75000,
    priceVisible: true,
    featured: false,
    sortOrder: 34,
    coverImage: "/gallery/states-of-attention/the-canvas-wouldnot-empty.jpg",
    images: [
      { id: "the-canvas-wouldnot-empty-cover", url: "/gallery/states-of-attention/the-canvas-wouldnot-empty.jpg", alt: "The Canvas Wouldnot Empty — Shivjeet Potdar, Acrylic on Ivory paper", kind: "cover", caption: null, width: 2400, height: 1874, sortOrder: 0 },
      { id: "the-canvas-wouldnot-empty-installation", url: "/gallery/states-of-attention/the-canvas-wouldnot-empty-context.jpg", alt: "The Canvas Wouldnot Empty — installation view", kind: "installation", caption: null, width: 2400, height: 1600, sortOrder: 1 },
    ],
    relatedSlugs: ["the-light-attracts-everything","symmetry-in-the-swarm","concentric-emergence"],
  },
  {
    ...base,
    id: "w-gallery-dance-of-duality",
    slug: "dance-of-duality",
    title: "Dance of Duality",
    year: null,
    yearSort: null,
    discipline: "art",
    kind: "Painting",
    medium: null,
    dimensions: null,
    summary: "From the Duality series.",
    description: [],
    statement: null,
    process: null,
    collectionSlug: "duality",
    availability: "enquire",
    price: null,
    priceVisible: false,
    featured: false,
    sortOrder: 35,
    coverImage: "/gallery/duality/dance-of-duality.jpg",
    images: [
      { id: "dance-of-duality-cover", url: "/gallery/duality/dance-of-duality.jpg", alt: "Dance of Duality — Shivjeet Potdar, painting", kind: "cover", caption: null, width: 2400, height: 1802, sortOrder: 0 },
      { id: "dance-of-duality-installation", url: "/gallery/duality/dance-of-duality-context.jpg", alt: "Dance of Duality — installation view", kind: "installation", caption: null, width: 2400, height: 1600, sortOrder: 1 },
    ],
    relatedSlugs: ["the-burden-of-goodness","the-infinite-axis","the-primordial-point"],
  },
  {
    ...base,
    id: "w-gallery-the-burden-of-goodness",
    slug: "the-burden-of-goodness",
    title: "The Burden of Goodness",
    year: null,
    yearSort: null,
    discipline: "art",
    kind: "Painting",
    medium: "Acrylic on Ivory paper",
    dimensions: "56 × 71 cm",
    summary: "A contemplative exploration of morality, pleasure, pain, and the identities we build around them, resolving into the open eye of consciousness at the centre.",
    description: [
      "The Burden of Goodness is a contemplative exploration of morality, pleasure, pain, and the subtle identities we create around them.",
      "The upper half represents goodness and pleasure — the part of us that knows what it wants and moves toward it. The eyes have pupils, symbolising awareness, direction, and desire. Yet every desire can carry its own attachments: fear, anger, jealousy, pride, and the fear of losing what we seek.",
      "The lower half represents pain, struggle, and surrender. The eyes have no pupils, suggesting a state that does not seek or grasp. Through struggle, sacrifice, and stepping beyond comfort, attachments can begin to dissolve.",
      "At the centre is the open eye of consciousness — awareness beyond the labels of good and bad, pleasure and pain. The partially closing eyelid becomes the final metaphor. The path from above is obstructed, while below it remains open. It suggests that even the identity of being good, or the desire for a higher state of awareness, can become another form of attachment.",
      "The painting ultimately asks: Who are you beyond the need to be good, bad, right, or wrong? And perhaps, more subtly: Can awakening be found when there is nothing left to seek?",
    ],
    statement: null,
    process: null,
    collectionSlug: "duality",
    availability: "available",
    price: 250000,
    priceVisible: true,
    featured: true,
    sortOrder: 36,
    coverImage: "/gallery/duality/the-burden-of-goodness.jpg",
    images: [
      { id: "the-burden-of-goodness-cover", url: "/gallery/duality/the-burden-of-goodness.jpg", alt: "The Burden of Goodness — Shivjeet Potdar, Acrylic on Ivory paper", kind: "cover", caption: null, width: 2400, height: 1802, sortOrder: 0 },
      { id: "the-burden-of-goodness-installation", url: "/gallery/duality/the-burden-of-goodness-context.jpg", alt: "The Burden of Goodness — installation view", kind: "installation", caption: null, width: 2400, height: 1600, sortOrder: 1 },
    ],
    relatedSlugs: ["dance-of-duality","the-infinite-axis","the-primordial-point"],
  },
  {
    ...base,
    id: "w-gallery-the-infinite-axis",
    slug: "the-infinite-axis",
    title: "The Infinite Axis",
    year: null,
    yearSort: null,
    discipline: "art",
    kind: "Painting",
    medium: null,
    dimensions: null,
    summary: "From the Duality series.",
    description: [],
    statement: null,
    process: null,
    collectionSlug: "duality",
    availability: "enquire",
    price: null,
    priceVisible: false,
    featured: false,
    sortOrder: 37,
    coverImage: "/gallery/duality/the-infinite-axis.jpg",
    images: [
      { id: "the-infinite-axis-cover", url: "/gallery/duality/the-infinite-axis.jpg", alt: "The Infinite Axis — Shivjeet Potdar, painting", kind: "cover", caption: null, width: 2400, height: 1802, sortOrder: 0 },
      { id: "the-infinite-axis-installation", url: "/gallery/duality/the-infinite-axis-context.jpg", alt: "The Infinite Axis — installation view", kind: "installation", caption: null, width: 2400, height: 1600, sortOrder: 1 },
    ],
    relatedSlugs: ["dance-of-duality","the-burden-of-goodness","the-primordial-point"],
  },
  {
    ...base,
    id: "w-gallery-the-primordial-point",
    slug: "the-primordial-point",
    title: "The Primordial Point",
    year: null,
    yearSort: null,
    discipline: "art",
    kind: "Painting",
    medium: null,
    dimensions: null,
    summary: "From the Duality series.",
    description: [],
    statement: null,
    process: null,
    collectionSlug: "duality",
    availability: "enquire",
    price: null,
    priceVisible: false,
    featured: false,
    sortOrder: 38,
    coverImage: "/gallery/duality/the-primordial-point.jpg",
    images: [
      { id: "the-primordial-point-cover", url: "/gallery/duality/the-primordial-point.jpg", alt: "The Primordial Point — Shivjeet Potdar, painting", kind: "cover", caption: null, width: 2400, height: 1802, sortOrder: 0 },
      { id: "the-primordial-point-installation", url: "/gallery/duality/the-primordial-point-context.jpg", alt: "The Primordial Point — installation view", kind: "installation", caption: null, width: 2400, height: 1600, sortOrder: 1 },
    ],
    relatedSlugs: ["dance-of-duality","the-burden-of-goodness","the-infinite-axis"],
  },
  {
    ...base,
    id: "w-gallery-untitled-i",
    slug: "untitled-i",
    title: "Untitled",
    year: null,
    yearSort: null,
    discipline: "art",
    kind: "Painting",
    medium: null,
    dimensions: null,
    summary: "From the Duality series — untitled in the material supplied by the artist.",
    description: [],
    statement: null,
    process: null,
    collectionSlug: "duality",
    availability: "enquire",
    price: null,
    priceVisible: false,
    featured: false,
    sortOrder: 39,
    coverImage: "/gallery/duality/untitled-i.jpg",
    images: [
      { id: "untitled-i-cover", url: "/gallery/duality/untitled-i.jpg", alt: "Untitled — Shivjeet Potdar, painting", kind: "cover", caption: null, width: 2400, height: 1802, sortOrder: 0 },
      { id: "untitled-i-installation", url: "/gallery/duality/untitled-i-context.jpg", alt: "Untitled — installation view", kind: "installation", caption: null, width: 2400, height: 1600, sortOrder: 1 },
    ],
    relatedSlugs: ["dance-of-duality","the-burden-of-goodness","the-infinite-axis"],
  },
  {
    ...base,
    id: "w-gallery-establishment-of-self",
    slug: "establishment-of-self",
    title: "Establishment of Self",
    year: "2026",
    yearSort: 2026,
    discipline: "art",
    kind: "Painting",
    medium: "Acrylic on paper",
    dimensions: "22 × 22 in",
    summary: "The first painting in the series — a mountain landscape crowned by a Shivling, a nest with one hatched and one unhatched egg, and the young bird's freedom to choose.",
    description: [
      "Establishment of Self is the first painting in the States of Awareness series. A mountain landscape crowned by a towering Shivling symbolizes the source of consciousness. Waterfalls descend into open grasslands before disappearing into a dense forest, representing the unfolding journey of life.",
      "In the foreground, a luminous nest with one hatched and one unhatched egg symbolizes birth and infinite potential. The young bird embodies the freedom to choose. Through choice, experience, and karma, the sense of self gradually takes form, inviting the viewer to reflect on identity as a process established through the life we choose to live.",
    ],
    statement: null,
    process: "Watch the process: https://youtu.be/NmezGg8lRSQ",
    collectionSlug: "states-of-awareness",
    availability: "sold",
    price: null,
    priceVisible: false,
    featured: false,
    sortOrder: 40,
    coverImage: "/gallery/states-of-awareness/establishment-of-self.jpg",
    images: [
      { id: "establishment-of-self-cover", url: "/gallery/states-of-awareness/establishment-of-self.jpg", alt: "Establishment of Self — Shivjeet Potdar, Acrylic on paper", kind: "cover", caption: null, width: 2346, height: 2400, sortOrder: 0 },
      { id: "establishment-of-self-installation", url: "/gallery/states-of-awareness/establishment-of-self-context.jpg", alt: "Establishment of Self — installation view", kind: "installation", caption: null, width: 2400, height: 1600, sortOrder: 1 },
    ],
    relatedSlugs: ["the-weight-of-i","the-observer","the-bliss"],
  },
  {
    ...base,
    id: "w-gallery-the-weight-of-i",
    slug: "the-weight-of-i",
    title: "The Weight of ‘I’",
    year: "2026",
    yearSort: 2026,
    discipline: "art",
    kind: "Painting",
    medium: "Acrylic on paper",
    dimensions: "22 × 22 in",
    summary: "The second painting — a luminous bird moving through a forest where light cannot reach the ground, and the fear that arrives with a formed identity.",
    description: [
      "The Weight of 'I' is the second painting in the States of Awareness series. A luminous bird journeys through a dense forest where light cannot reach the ground, symbolizing the mind after the formation of identity. As the sense of \"I\" emerges, so does the instinct to protect it.",
      "The painting reflects on fear as a natural consequence of attachment to the self, inviting the viewer to contemplate the burden of identity.",
    ],
    statement: null,
    process: "Watch the process: https://youtu.be/eYqfRj33NLo",
    collectionSlug: "states-of-awareness",
    availability: "sold",
    price: null,
    priceVisible: false,
    featured: false,
    sortOrder: 41,
    coverImage: "/gallery/states-of-awareness/the-weight-of-i.jpg",
    images: [
      { id: "the-weight-of-i-cover", url: "/gallery/states-of-awareness/the-weight-of-i.jpg", alt: "The Weight of ‘I’ — Shivjeet Potdar, Acrylic on paper", kind: "cover", caption: null, width: 2346, height: 2400, sortOrder: 0 },
      { id: "the-weight-of-i-installation", url: "/gallery/states-of-awareness/the-weight-of-i-context.jpg", alt: "The Weight of ‘I’ — installation view", kind: "installation", caption: null, width: 2400, height: 1600, sortOrder: 1 },
    ],
    relatedSlugs: ["establishment-of-self","the-observer","the-bliss"],
  },
  {
    ...base,
    id: "w-gallery-the-observer",
    slug: "the-observer",
    title: "The Observer",
    year: "2026",
    yearSort: 2026,
    discipline: "art",
    kind: "Painting",
    medium: "Acrylic on paper",
    dimensions: "22 × 22 in",
    summary: "Deep in the forest, the bird meets a still Nilgai — and realises thoughts, emotions and fear need not be identified with, only observed.",
    description: [
      "The Observer is the third painting in the States of Awareness series. Deep within the dense forest, the bird encounters a still Nilgai, symbolizing awareness. In this silent meeting, the bird realizes that thoughts, emotions, and fear need not be identified with — they can simply be observed.",
      "The painting marks the shift from attachment to witnessing, revealing awareness as the quiet presence behind every experience.",
    ],
    statement: null,
    process: "Watch the process: https://youtu.be/vYGxbBO68tA",
    collectionSlug: "states-of-awareness",
    availability: "sold",
    price: null,
    priceVisible: false,
    featured: true,
    sortOrder: 42,
    coverImage: "/gallery/states-of-awareness/the-observer.jpg",
    images: [
      { id: "the-observer-cover", url: "/gallery/states-of-awareness/the-observer.jpg", alt: "The Observer — Shivjeet Potdar, Acrylic on paper", kind: "cover", caption: null, width: 2346, height: 2400, sortOrder: 0 },
      { id: "the-observer-installation", url: "/gallery/states-of-awareness/the-observer-context.jpg", alt: "The Observer — installation view", kind: "installation", caption: null, width: 2400, height: 1600, sortOrder: 1 },
    ],
    relatedSlugs: ["establishment-of-self","the-weight-of-i","the-bliss"],
  },
  {
    ...base,
    id: "w-gallery-the-bliss",
    slug: "the-bliss",
    title: "The Bliss",
    year: "2026",
    yearSort: 2026,
    discipline: "art",
    kind: "Painting",
    medium: "Acrylic on paper",
    dimensions: "22 × 22 in",
    summary: "Guided by fireflies, the bird rises above the forest into the open sky, witnessing light and darkness as parts of the same whole.",
    description: [
      "The Bliss is the fourth painting in the States of Awareness series. Guided by a swarm of fireflies, the bird rises above the forest into the open sky, where it witnesses both light and darkness as parts of the same whole.",
      "The painting symbolizes the joy that arises from awareness — not through escaping the world, but through seeing it with clarity, freedom, and an unburdened mind.",
    ],
    statement: null,
    process: "Watch the process: https://youtu.be/h4R5qXem2ys",
    collectionSlug: "states-of-awareness",
    availability: "sold",
    price: null,
    priceVisible: false,
    featured: false,
    sortOrder: 43,
    coverImage: "/gallery/states-of-awareness/the-bliss.jpg",
    images: [
      { id: "the-bliss-cover", url: "/gallery/states-of-awareness/the-bliss.jpg", alt: "The Bliss — Shivjeet Potdar, Acrylic on paper", kind: "cover", caption: null, width: 2346, height: 2400, sortOrder: 0 },
      { id: "the-bliss-installation", url: "/gallery/states-of-awareness/the-bliss-context.jpg", alt: "The Bliss — installation view", kind: "installation", caption: null, width: 2400, height: 1600, sortOrder: 1 },
    ],
    relatedSlugs: ["establishment-of-self","the-weight-of-i","the-observer"],
  },
  {
    ...base,
    id: "w-gallery-a-small-fire",
    slug: "a-small-fire",
    title: "A Small Fire",
    year: "2026",
    yearSort: 2026,
    discipline: "art",
    kind: "Painting",
    medium: "Acrylic on paper",
    dimensions: "22 × 22 in",
    summary: "From above the forest, the bird watches a fire burning in the valley below — overwhelming up close, small within the whole landscape.",
    description: [
      "A Small Fire is the fifth and final painting in the States of Awareness series. From above the forest, the bird witnesses a fire burning in the valley below. What once might have appeared overwhelming is now seen within the vastness of the landscape.",
      "The painting reflects on perspective, reminding us that the mind often magnifies its struggles, while awareness reveals them as fleeting moments within a much larger whole.",
    ],
    statement: null,
    process: "Watch the process: https://youtu.be/K19KNbITkhk",
    collectionSlug: "states-of-awareness",
    availability: "sold",
    price: null,
    priceVisible: false,
    featured: false,
    sortOrder: 44,
    coverImage: "/gallery/states-of-awareness/a-small-fire.jpg",
    images: [
      { id: "a-small-fire-cover", url: "/gallery/states-of-awareness/a-small-fire.jpg", alt: "A Small Fire — Shivjeet Potdar, Acrylic on paper", kind: "cover", caption: null, width: 2346, height: 2400, sortOrder: 0 },
      { id: "a-small-fire-installation", url: "/gallery/states-of-awareness/a-small-fire-context.jpg", alt: "A Small Fire — installation view", kind: "installation", caption: null, width: 2400, height: 1600, sortOrder: 1 },
    ],
    relatedSlugs: ["establishment-of-self","the-weight-of-i","the-observer"],
  },
];
